[BE] 이미지 업로드
issue-tracker-08/issue-tracker-max pull request #66
Opened 2023-08-01 08:22 UTC by HyowonSin

## Issues
- #61 

## What is this PR? 👓
- 이미지 업로드 기능

## Key changes 🔑
- s3 관련 의존성 추가
- aws s3 config 추가
- file controller 에서 이미지 파일 폼데이터로 받고 S3 객체 주소 리턴
- s3 서비스 추가 (실제 업로드 하는 로직)

## To reviewers 👋
- application-KEYS.yml 은 슬랙으로 공유하겠습니다. 혹은 실행만 한다면 밸류를 인텔리제이 환경 변수로 넣는 방법도 있습니다.
- FileController 라고 만들어두긴 했는데 코멘트에만 쓰여서 CommentController 에 넣을지?

2023-08-01 08:59 UTC, pie2457 approved these changes
잘 봤습니다 수고하셨어요 ! 👍🏼

2023-08-01 08:59 UTC, pie2457 commented on backend/src/main/resources/application-dev.yml
> +      bucket: ${aws.s3.bucket}
`-` 표시가 뜨는 이유를 아시나요!?
[EOL](https://velog.io/@jangws/EOL%EC%9D%84-%EB%84%A3%EC%96%B4%EC%95%BC-%ED%95%98%EB%8A%94-%EC%9D%B4%EC%9C%A0%EC%99%80-git%EC%97%90%EC%84%9C-CRLF-EOL-%EC%B0%A8%EC%9D%B4%EB%A1%9C-%EC%9D%B8%ED%95%9C-%EB%AC%B8%EC%A0%9C-%ED%95%B4%EA%B2%B0-%EB%B0%A9%EB%B2%95)을 찾아보시면 좋을거같습니다!

2023-08-01 08:59 UTC, pie2457 commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +            throw new IllegalArgumentException("file이 존재하지 않습니다.");
커스텀 예외를 만들어 던지면 더 좋을꺼 같아요 !

2023-08-01 09:01 UTC, 23Yong requested changes
파일 업로드도 하나의 기능(API)이기 때문에 `FileController`에 있는게 좋을 것 같습니다!

리뷰사항 확인해서 수정하면 좋을 것 같아요!

2023-08-01 09:01 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +        String dirName = "public/uploaded-images/";
`dirName`은 항상 같으니까 상수로 빼는 건 어떤가요?

2023-08-01 09:01 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +        String contentType = getContentType(fileName.substring(fileName.lastIndexOf(".")));
`getContentType`메서드 보다는 FileExtension이라는 enum을 만들어서 제한된 확장자만 가지도록 하는건 어떨까요?

2023-08-01 09:01 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +    }
해당 메서드는 ImageFile 클래스를 하나 만들어서 도메인으로 보는 건 어떠세요?
```java
public class ImageFile {

	private final String originalFilename;
	private final String contentType;

	public ImageFile(String originalFilename, String contentType, byte[] imageBytes) {
		this.originalFilename = originalFilename;
		this.contentType = contentType;
		this.imageBytes = imageBytes;
	}

	public String getRandomName() {
		StringBuilder randomName = new StringBuilder();
		randomName.append(UUID.randomUUID())
			.append(".")
			.append(StringUtils.getFilenameExtension(originalFilename));

		return randomName.toString();
	}

	public static ImageFile from(MultipartFile multipartFile) {
		try {
			return new ImageFile(
				multipartFile.getOriginalFilename(),
				multipartFile.getContentType());
		} catch (IOException e) {
			throw new BusinessException("잘못된 이미지 파일입니다.", ErrorCode.FILE_INVALID);
		}
	}
}
```

뭔가 이런느낌으로..?

2023-08-01 09:01 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +        if (Objects.isNull(file) || file.isEmpty()) {
코드로 알 수 있는 주석은 제거하면 좋을 것 같아요!
37, 40, 43, 47

2023-08-01 09:01 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +    private final AmazonS3Client amazonS3Client;
한 줄 띄워주세용~
```java
public class S3Service {

    private final AmazonS3Client amazonS3Client;
```

2023-08-01 09:01 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/issuetracker/presentation/FileController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(Map.of("fileUrl" ,s3Service.uploadImage(image)));
`Controller`에서 `IOException`을 던지는 건 좋지 않은 것 같아요.
Service 레이어에서 처리하거나 예외가 발생한 곳에서 처리하는 건 어떨까요?

2023-08-01 09:01 UTC, 23Yong commented on backend/src/main/resources/application.yml
> +      - KEYS
`KEYS`는 `application-KEYS.yml` 인건가요?

만약 맞다면 ignore 처리하고 include에 있는게 자연스러운 것 같아요!

2023-08-01 09:01 UTC, 23Yong commented on backend/src/main/resources/application.yml
> +      - jwt
마지막 공백 라인은 넣어주세요~

2023-08-01 09:01 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/issuetracker/infrastructure/config/S3Config.java
> +
`@ConfigurationProperties`를 사용하는 건 어떨까요?
JWT도 그렇게 해서 일관되게 가져가면 좋을 것 같아서요!

2023-08-01 09:01 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/issuetracker/infrastructure/config/S3Config.java
> +    @Value("${cloud.aws.credentials.access-key}")
여기도 한 줄 띄워주세용~
```java
public class S3Config {

    private String secretKey;
```

2023-08-01 09:01 UTC, 23Yong commented on backend/src/main/resources/application-dev.yml
> +      bucket: ${aws.s3.bucket}
공백 라인을 추가해주세요!

2023-08-01 09:01 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +        // 업로드한 파일의 URL을 받아올 변수
`IOException`을 던지지말고 예외 처리하는게 좋을 것 같아요!

2023-08-02 00:37 UTC, HyowonSin commented on backend/src/main/resources/application-dev.yml
> +      bucket: ${aws.s3.bucket}
앗 넵넵 마지막에 확인을 잊었네요..!
수정하겠습니다!!

2023-08-02 00:38 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +            throw new IllegalArgumentException("file이 존재하지 않습니다.");
맞네요!!
수정하겠습니다!!

2023-08-02 00:42 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +        String contentType = getContentType(fileName.substring(fileName.lastIndexOf(".")));
이게 파일의 확장자를 찾아서 메타데이터를 추가해주는 과정이라
찾는 과정이 들어가긴 할 것 같습니다!
뒷 부분에서 enum 으로 제한하는 것을 적용해보겠습니다

2023-08-02 00:42 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +    }
오 좋은 방법 감사합니다
적용해볼게요!!

2023-08-02 00:42 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +        if (Objects.isNull(file) || file.isEmpty()) {
네 수정하겠습니다!

2023-08-02 00:42 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +    private final AmazonS3Client amazonS3Client;
헉.. ㅋ

2023-08-02 00:51 UTC, HyowonSin commented on backend/src/main/resources/application.yml
> +      - KEYS
아하 제가 둘의 차이를 잘 몰라서 좀 찾아봤는데
active 는 하나의 yml 에서 프로필을 여러개로 나눠서 하는 거 같고
include 는 다른 파일을 말하는 것 같기도 하네요
include 가 적합해 보이네요 감사합니다!

2023-08-02 01:59 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +        String dirName = "public/uploaded-images/";
아마 댓글에서 이미지업로드와 
회원의 프로필사진 정도로만 나뉠 것 같긴 합니다
2개니까 상수로 빼볼게요~

2023-08-02 02:25 UTC, tjdqls1200 approved these changes
코드 잘 봤습니다! 수고하셨습니다~

2023-08-02 02:25 UTC, tjdqls1200 commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +            case ".png":
enum 클래스를 만들어도 좋을 것 같습니다!

2023-08-02 02:25 UTC, tjdqls1200 commented on backend/src/main/java/kr/codesquad/issuetracker/presentation/FileController.java
> +    @PostMapping("/upload")
"/api/files/upload" 또는 "/api/files"로 어떤 리소스인지 명시해주면 좋을 것 같습니다.

2023-08-02 05:31 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/issuetracker/presentation/FileController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(Map.of("fileUrl" ,s3Service.uploadImage(image)));
처리완

2023-08-02 05:33 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +            case ".png":
넵 반영했습니다!

2023-08-02 05:33 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/issuetracker/presentation/FileController.java
> +    @PostMapping("/upload")
네 그러면
images/upload 로 하겠습니다
명세 수정할게요

2023-08-02 05:47 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +    }
도메인으로 본다는건 하나의 문제 영역으로 본다는 의미였어요!
말씀대로 DB에서 관리할 필요까지는 없어보입니당

2023-08-02 05:59 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/issuetracker/infrastructure/config/S3Config.java
> +
저희 상황에서 @ConfigurationProperties 를 사용해서 더 좋은 점이 어떤 것인가요?

2023-08-02 06:00 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +    }
넵넵 반영해보겠습니다~

2023-08-02 07:13 UTC, 23Yong approved these changes
수고하셨습니다!
`@ConfigurationProperties`는 아직 적용안하신건가용?

2023-08-02 07:13 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +        ImageFile imageFile = ImageFile.from(file);
👍
그런데 28라인 공백은 지워주세요ㅎㅎㅋㅋㅋ

2023-08-02 07:13 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +    private static final String UPLOADED_IMAGES = "public/uploaded-images/";
UPLOADED_IMAGES_DIR 은 어떠세요?

2023-08-02 07:13 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
>                  .withCannedAcl(CannedAccessControlList.PublicRead));
34-39라인을 메서드로 분리할 수 있을까요?
```java
private void uploadImageToS3(ImageFile imageFile) {
        ObjectMetadata metadata = new ObjectMetadata();
        metadata.setContentType(imageFile.getContentType());
        metadata.setContentLength(file.getSize());
        amazonS3Client.putObject(new PutObjectRequest(bucket, fileName, imageFile.getImageInputStream(), metadata)
            .withCannedAcl(CannedAccessControlList.PublicRead));
}
```

2023-08-02 07:13 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +        return URLDecoder.decode(amazonS3Client.getUrl(bucket, fileName).toString(), StandardCharsets.UTF_8);
이 부분도 메서드로 분리하는건 어때요?
```java
private String getDecodedImageUrl(String fileName) {
    return URLDecoder.decode(amazonS3Client.getUrl(bucket, fileName).toString(), StandardCharsets.UTF_8);
}
```

2023-08-02 07:15 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +        ImageFile imageFile = ImageFile.from(file);
ㅠㅠ

2023-08-02 07:16 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +    private static final String UPLOADED_IMAGES = "public/uploaded-images/";
굿입니다

2023-08-02 07:30 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
>                  .withCannedAcl(CannedAccessControlList.PublicRead));
넵넵!

2023-08-02 07:30 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/issuetracker/application/S3Service.java
> +        return URLDecoder.decode(amazonS3Client.getUrl(bucket, fileName).toString(), StandardCharsets.UTF_8);
같이 했습니다!

2023-08-02 08:18 UTC, 23Yong commented on backend/src/main/java/kr/codesquad/issuetracker/domain/ImageFile.java
> +        return new ImageFile(multipartFile);
```java
public class ImageFile {

	private final String originalFilename;
	private final String contentType;
	private final byte[] imageBytes;
```
```java
validateMultipartFile(multipartFile);
  try {
        return new ImageFile(
	        multipartFile.getOriginalFilename(),
	        multipartFile.getContentType(),
	        multipartFile.getBytes()
        );
  } catch(IOException e) {
      ~
  }
}
```
```java
public InputStream getImageInputStream() {
    return new ByteArrayInputStream(imageBytes);
|
```
로도 할 수 있을듯 싶습니당? try - catch 한 곳으로 몰기..?

2023-08-08 02:11 UTC, HyowonSin commented on backend/src/main/java/kr/codesquad/issuetracker/domain/ImageFile.java
> +        return new ImageFile(multipartFile);
반영했습니다!
다만 인풋스트림은 꺼낼 때 무조건 IO 핸들링이 필요하네요,,

2023-08-08 02:25 UTC, merged